SELECT FP.PRODUCT_ID,FP.PRODUCT_NAME,FP.PRICE * FO.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
      FROM FOOD_ORDER
      WHERE PRODUCE_DATE BETWEEN "2022-05-01" AND "2022-05-31"
      GROUP BY PRODUCT_ID) AS FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
GROUP BY FP.PRODUCT_ID 
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID 