SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW A #JOIN기준 테이블
INNER JOIN REST_INFO B ON A.REST_ID = B.REST_ID #조건은 REST_ID
GROUP BY A.REST_ID # REST_ID로 정렬
HAVING B.ADDRESS LIKE '서울%' #서울로 시작하는 단어
ORDER BY SCORE DESC, B.FAVORITES DESC
